os: linux
dist: trusty

language: node_js
node_js:
  - "stable"
  - "latest"
  - 8
  - 10

cache:
  yarn: true

script:
  - yarn lint
  - yarn build
  - yarn test

after_script:
  - yarn add -D codacy-coverage
  - cat ./coverage/lcov.info | codacy-coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
