os: linux
dist: trusty

language: node_js
node_js:
  - stable
  - lts/*

cache:
  yarn: true

script:
  - yarn lint
  - yarn build
  - yarn test

jobs:
  include:
    - stage: coverage push
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn test
          - yarn add -D codacy-coverage
          - cat ./coverage/lcov.info | codacy-coverage

    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
